name: golangci-lint
on:
  push:
    branches: ["master","dev"]  
  pull_request:
    branches: ["master","dev"]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Install golangci-lint
      run: |
        GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.30.0
    - name: Lint code
      run: golangci-lint run
